#! /bin/bash
  
if [ "$1" == "-h" ]
then
    echo "Soy ayuda"

elif [ "$#" > "1" ]
then
    if [ "$1" == "-f" ]
    then
        echo "Usuarios     Tiempo"
        cat $2 |tr -s " " > salida.txt
        cut -d " " -f 1,10 salida.txt
    elif [ "$1" == "-u" ]
    then
        echo "Datos     Tiempo"
        grep $2 $4 |tr -s " " > salida.txt
        cut -d " " -f 1,10 salida.txt
    fi
fi
