#! /bin/bash
  
if [ "$1" == "-h" ]
then
    echo "Soy ayuda"

elif [ "$#" > "1" ]
then
    if [ "$1" == "-f" ]
    then
           cat usuarios260820.txt
    elif [ "$1" == "-u" ]
    then
            grep $2 $4 usuarios260820.txt > salida.txt
    fi
fi
